### ISSUE TITLE
✨[Feature Request]: Replacemnt of Chatbot

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#461] opened 2024-06-06 20:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Assist about rapidoc to user's.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/8cc42a81-3111-40bf-b783-651915593c40)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment] 2024-06-06 20:29
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/ec680550-ed8f-49a3-b4e0-5ce0aa4ef7c5)


![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/5a8f5166-c340-4a58-a863-9e18c6a0801e)

**Comment by Anjaliavv51** [comment] 2024-06-06 20:30
@varshith257  @Anishkagupta04 i want to add Chatbot to the website.
please assign me this issue under GSSOC.
If possible please add Level 3 label.

**Comment by Anjaliavv51** [comment] 2024-06-06 20:46
@varshith257 @Anishkagupta04  as the chatbot is having havingsome issue with code , so i created another new chatbot.

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/af2b9654-a3ba-455c-b7ea-d65396366a6f)

**Comment by varshith257** [comment] 2024-06-07 02:38
@Anjaliavv51 Already a chatbot have been integrated

**Comment by Anjaliavv51** [comment] 2024-06-07 02:47
@varshith257 is it working?

**Comment by varshith257** [comment] 2024-06-07 02:48
Here's the PR of it:
- #384

**Comment by Anjaliavv51** [comment] 2024-06-07 02:49
@varshith257 that I sas , will i wam exploring ur site in raw

**Comment by Anjaliavv51** [comment] 2024-06-07 02:51
@varshith257 chatbpt is not in proper manner

**Comment by Anjaliavv51** [comment] 2024-06-07 02:52
It is like a bar one near the header.

**Comment by varshith257** [comment] 2024-06-07 02:52
@Anjaliavv51 Didn't get it

**Comment by Anjaliavv51** [comment] 2024-06-07 02:53
@varshith257 please wait a minute i will send the screenshot

**Comment by Anjaliavv51** [comment] 2024-06-07 02:55
@varshith257 

![SmartSelect_20240607_082435_Chrome.jpg](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/26f07808-24c2-4c14-bcf6-bf50ae451219)

Please check the pic

**Comment by varshith257** [comment] 2024-06-07 03:00
Yes, that's am issue before the above PR merged. Pull latest upstream and check it once

**Comment by Anjaliavv51** [comment] 2024-06-07 03:01
@varshith257 
But still It is appearing like that , once view the output of website

**Comment by varshith257** [comment] 2024-06-07 03:13
> But still It is appearing like that , once view the output of website 

@Hemashree21 @samarsajad @Pruthaa17 

Can you check this and is it the same appearing to you?

**Comment by Anjaliavv51** [comment] 2024-06-07 03:23
@varshith257 please check , i viewed it in other device , still it appearing like below.

![WhatsApp Image 2024-06-07 at 08 50 09_b3b36345](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/2547b6be-08e1-4d29-b796-7490843974aa)

![WhatsApp Image 2024-06-07 at 08 51 02_6c8756e2](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/011eabc9-8e40-413d-bb07-391f4e4c682e)

**Comment by varshith257** [comment] 2024-06-07 03:26
Isn't the #384 PR changes added to codebase?

**Comment by Pruthaa17** [comment] 2024-06-07 03:36
@varshith257 The Landing page is fine before and after doing **sync fork**

**Comment by Anjaliavv51** [comment] 2024-06-07 03:37
> Aren't the #384 PR changes added to the codebase?

u r asking in my codebase?

**Comment by varshith257** [comment] 2024-06-07 03:40
Here in main

**Comment by Pruthaa17** [comment] 2024-06-07 03:49
Main seems fine ! @varshith257

**Comment by varshith257** [comment] 2024-06-07 03:50
> @varshith257 The Landing page is fine before and after doing **sync fork**

@Pruthaa17 For the chatbot. Aren't you view the changes added from #384 PR

**Comment by Pruthaa17** [comment] 2024-06-07 03:56
Landing page which i can see currently  in main is like this 
![Screenshot (421)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/922ef106-63de-4280-9be0-9d459483b49c)

**Comment by Hemashree21** [comment] 2024-06-07 04:01
@varshith257  It's showing like this
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/138188163/a415e0bf-52ed-4c84-9386-4ae2d5e5bb45)

**Comment by varshith257** [comment] 2024-06-07 04:04
@sidhigrover Take a look. Your PR work wasn't reflected here

**Comment by sidhigrover** [comment] 2024-06-07 04:39
> @sidhigrover Take a look. Your PR work wasn't reflected here

@varshith257 When you merged my pull request, the chatbot was properly aligned. It seems that someone might have made changes after that.

**Comment by varshith257** [comment] 2024-06-07 04:40
@sidhigrover Once you check the current code and your changes in that PR and submit another PR for your changes

**Comment by sidhigrover** [comment] 2024-06-07 04:42
> @sidhigrover Once you check the current code and your changes in that PR and submit another PR to reflect the same changes

ok

**Comment by varshith257** [comment] 2024-06-07 13:38
@Anjaliavv51 Chheck it now. merged a PR with changes

**Comment by Anjaliavv51** [comment] 2024-06-07 13:43
PR number?
@richasriva

**Comment by Anjaliavv51** [comment] 2024-06-07 13:44
@varshith257

**Comment by varshith257** [comment] 2024-06-07 13:46
#465

**Comment by varshith257** [comment] 2024-06-07 13:47
Pull latest upstream and verify it once

**Comment by Anjaliavv51** [comment] 2024-06-07 13:49
@varshith257 , it is not responding

**Comment by Anjaliavv51** [comment] 2024-06-07 13:49
@varshith257 chatbot is not responding

**Comment by Anjaliavv51** [comment] 2024-06-07 13:51
> Pull latest upstream and verify it once

it is latest

**Comment by sidhigrover** [comment] 2024-06-07 13:56
> @varshith257 chatbot is not responding
> 
> ![image](https://private-user-images.githubusercontent.com/154777864/337676507-e6a500e4-f872-40e1-b763-aaf0b60f614b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Njg4MzgsIm5iZiI6MTcxNzc2ODUzOCwicGF0aCI6Ii8xNTQ3Nzc4NjQvMzM3Njc2NTA3LWU2YTUwMGU0LWY4NzItNDBlMS1iNzYzLWFhZjBiNjBmNjE0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMzU1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzZjMjMyYTRiYjA1ZDNmZGQ2ZDZmNDY2YjgzODFmYzQyOGE0MjY3OWNhYTQ3YWY2YWQxOTVlYmM0MWQwZGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cmyds5lv7QTLAYtYTzziNXHmKlsRwNdUbzw2sXPl_2k)

You have to write hi on it...not hlo

**Comment by Anjaliavv51** [comment] 2024-06-07 13:57
@sidhigrover let me check

**Comment by Anjaliavv51** [comment] 2024-06-07 13:58
@sidhigrover 

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/8e5b5f36-1b02-4879-949b-0bca1486cab7)


@sidhigrover chatbot should respond to every question

**Comment by Anjaliavv51** [comment] 2024-06-07 13:58
please check it and modify

**Comment by sidhigrover** [comment] 2024-06-07 14:03
> please check it and modify

You have to click on questions

**Comment by Anjaliavv51** [comment] 2024-06-07 14:07
> > please check it and modify
> 
> You have to click on questions

then what is the use of Chatbot @sidhigrover

**Comment by varshith257** [comment] 2024-06-07 14:08
@Anjaliavv51 As you are interested in contributing to this chatbot feature. My suggestion is to integrate a GPT API for the existing chatbot to make it more engaging chatbot

**Comment by varshith257** [comment] 2024-06-07 14:09
> > > please check it and modify
> > 
> > 
> > You have to click on questions
> 
> then what is the use of Chatbot @sidhigrover

The issue is that API isn't working. So instead replaced with manual Q&A

**Comment by Anjaliavv51** [comment] 2024-06-07 14:11
> @Anjaliavv51 As you are interested in contributing to this chatbot feature. My suggestion is to integrate a GPT API for the existing chatbot to make it more engaging chatbot

@varshith257 it is chatbot is already ready

**Comment by Anjaliavv51** [comment] 2024-06-07 14:11
tell me give the preview of it

**Comment by varshith257** [comment] 2024-06-07 14:13
> tell me show u the preview of it

Didn't get it

**Comment by Anjaliavv51** [comment] 2024-06-07 14:14
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/7478052f-1704-4d40-a105-33a0d617cd1b



> > tell me show u the preview of it
> 
> Didn't get it

😆 sorry @varshith257 i am saying let me show the preview

**Comment by Anjaliavv51** [comment] 2024-06-07 15:12
@varshith257 please assign me this issue

**Comment by Anjaliavv51** [comment] 2024-06-07 15:18
@varshith257 please review the PR

**Closed** 2024-06-07 16:39 UTC
Labels: enhancement, gssoc
