### ISSUE TITLE
missing code of conduct 

### ISSUE THREAD

**Issue by prajwaldp223** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#95] opened 2024-05-13 19:38 UTC
this repo is missing with the code of conduct file and i acn do it is assigned to me under gssoc !!

**Comment by Anishkagupta04** [comment] 2024-05-14 06:29
assigning to you

**Comment by prajwaldp223** [comment] 2024-05-14 11:10
@Anishkagupta04 ,can u assign this to me under gssoc label?

**Comment by varshith257** [comment] 2024-05-14 11:43
@prajwaldp223 Closing as duplicate of  
- #16

**Closed** 2024-05-14 11:43 UTC
Labels: documentation, enhancement, GSSOC 2024, Level 1

**Comment by prajwaldp223** [comment] 2024-05-14 12:07
@varshith257 !!
should i raise sepetate for both?

**Comment by prajwaldp223** [comment] 2024-05-14 12:44
ok

**Comment by prajwaldp223** [comment] 2024-05-14 12:54
but the other one is named as duplicate!! can u recheck it!! as i have deleted a file PRfile from request and crated new PR #111

**Comment by varshith257** [comment] 2024-05-14 13:11
Check PR #16
