### ISSUE TITLE
💡[FEATURE]: add dark mode

### ISSUE THREAD

**Issue by Muskan130803** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#110] opened 2024-05-14 12:06 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by varshith257** [comment] 2024-05-14 14:39
Closing as duplicate of #23

**Closed by varshith257** 2024-05-14 14:39 UTC
Labels: enhancement
