### ISSUE TITLE
💡[FEATURE, BUG]:  Mobile layout and other issues

### ISSUE THREAD

**Issue by Rajput-xv** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#101] opened 2024-05-14 08:10 UTC
I would like to make this website for mobile users like changing all layout and some designs.
@Anishkagupta04  if u would assign this to me.

Additionally, I would also like to make some changes to existing design to make it better.
like some places the content is too close to its boundary.
the width of website is exceeding the window size.
the video shown besides header its bottom is visible from below card section.

**Comment by varshith257** [comment] 2024-05-14 08:43
@Anishkagupta04 PTAL. It seems duplicate of an issue

**Closed** 2024-06-18 06:38 UTC
Labels: enhancement
