### ISSUE TITLE
✨[Feature Request]: Add Privacy Policy Page 

### ISSUE THREAD

**Issue by Pruthaa17** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#383] opened 2024-05-31 18:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The footer of the page shows privacy policy option , but the website doesn't have one  

### Use Case

To inform visitors about how a website processes data in accordance with relevant data regulations so the privacy policy page plays an important role 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ananya-Nair20** [comment] 2024-06-01 08:49
Hello @Anishkagupta04 

I am participating in GSSOC'24. I am interested in resolving this issue. Please assign this issue to me under GSSOC'24 with appropriate level labels.

Thank you

**Comment by varshith257** [comment] 2024-06-01 09:32
Closing duplicate of #378

**Closed by varshith257** 2024-06-01 09:32 UTC
Labels: enhancement, gssoc
