### ISSUE TITLE
✨[Feature Request]: feature adding Improvement in the Appointment page.

### ISSUE THREAD

**Issue by agrwal697** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#480] opened 2024-06-07 16:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I think if the appointment section had a border-bottom in every text item so it would have better UI .I would also like to make it responsive.
Please Assign me this issue with the label of GSSOC.

### Use Case

had a border-bottom in every text item so it would have better UI of the website .

### Add ScreenShots

Before:

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/128716726/b085db65-1be7-49a8-a0e5-44fa71bb12d7)

After:

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/128716726/08dc01b8-bb5a-4050-8ef6-0dcea3705fea)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment] 2024-06-08 16:01
We already have an issue for it #273

**Comment by varshith257** [comment] 2024-06-08 16:03
Closing as duplicate of #263

**Closed** 2024-06-08 16:03 UTC
